Chart filebeat
Ubivius/telemetry-filebeat pull request #1
Opened 2021-09-02 23:37 UTC by MaximeStOnge

#### What changes does this PR contain?
Filebeat chart

#### Which JIRA ticket ID's are associated with this PR?
UBI-450

#### Additional comments and information

2021-09-07 14:49 UTC, ArcticWalrus approved these changes

2021-09-16 00:25 UTC, ysma500 requested changes

2021-09-16 00:25 UTC, ysma500 commented on chart/values.yaml
> +    cpu: 25m # default 100m
Get delta between requested and limits smaller

2021-09-29 20:21 UTC, ysma500 approved these changes
LGTM :-)

2021-09-29 22:18 UTC, merged